### ISSUE TITLE
problem with mrt

### ISSUE THREAD

**Issue by rohan718** [t2mune/mrtparse#1]
hi sir, when I run this code:$ cd " clone directory  "
the ubunto said = syntax error near unexpected token `newline' 
what's the problem? ' i have done all of the step i mean download that code.

**Comment by t2mune** [comment]
" clone directory " represents the directory, that git clone command created.

Here is my log:

t2mune@ubuntu13-openstack:~$ git clone https://github.com/YoshiyukiYamauchi/mrtparse.git
Cloning into 'mrtparse'...
remote: Reusing existing pack: 907, done.
Receiving objects: 100% (907/907), 2.36 MiB | 569.00 KiB/s, done.
remote: Total 907 (delta 0), reused 0 (delta 0)
Resolving deltas: 100% (509/509), done.
Checking connectivity... done
t2mune@ubuntu13-openstack:~$ cd mrtparse
t2mune@ubuntu13-openstack:~/mrtparse$ sudo python setup.py install
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying mrtparse.py -> build/lib.linux-x86_64-2.7
running install_lib
copying build/lib.linux-x86_64-2.7/mrtparse.py -> /usr/local/lib/python2.7/dist-packages
byte-compiling /usr/local/lib/python2.7/dist-packages/mrtparse.py to mrtparse.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/mrtparse-1.0.egg-info
t2mune@ubuntu13-openstack:~/mrtparse

**Comment by t2mune** [comment]
Did it go well?

**Comment by rohan718** [comment]
hi again sir - I think , we(my classmate and I) have big problem with this code and it causes to more study about code in Ubunto, we don't want to take your time,but really need this code to install and initial the TCAM in my project, it's about IP lookup in Ipv6 so we need real bgptable like your example but we can't open it.

**Comment by t2mune** [comment]
Could you show me your log to check the problem?

**Comment by YoshiyukiYamauchi** [comment]
Hi, rohan718
I want to check your log, too.
Here is my log on Ubuntu Server 14.04 LTS

``` sh
yoshiyuki@ubuntu:~$ git clone https://github.com/YoshiyukiYamauchi/mrtparse.git
Cloning into 'mrtparse'...
remote: Reusing existing pack: 907, done.
Receiving objects: 100% (907/907), 2.36 MiB | 648.00 KiB/s, done.
remote: Total 907 (delta 0), reused 0 (delta 0)
Resolving deltas: 100% (509/509), done.
Checking connectivity... done
yoshiyuki@ubuntu:~$ cd mrtparse
yoshiyuki@ubuntu:~$ ls
ChangeLog  LICENSE  README-ja.md  README.md  examples  mrtparse.py  setup.py
```

**Comment by rohan718** [comment]
hi sir again 
thanks for your reply , 

rohan026@ubuntu:~$ cd mrtparse
rohan026@ubuntu:~/mrtparse$ ls
build      examples  mrtparse.py   README-ja.md  setup.py
ChangeLog  LICENSE   mrtparse.pyc  README.md
rohan026@ubuntu:~/mrtparse$ 

after that I installed the Python but I don't know after that what should i to do,

**Comment by YoshiyukiYamauchi** [comment]
Hi, rohan718

Thank you for your log, here is usage.

## Install

``` sh
$ cd mrtparse
$ sudo python setup.py install
running install
running build
running build_py
running install_lib
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/mrtparse-1.0.egg-info
```

## Download MRT format data

EXAMPLE - from RIPE(http://data.ris.rpe.inet/rrc00/)

``` sh
$ cd example
$ sudo wget http://data.ris.ripe.net/rrc00/latest-update.gz
```

## Displays the contents of a MRT format file

``` sh
$ python print_all.py latest-update.gz
---------------------------------------------------------------
MRT Header
    Timestamp: 1392828028(2014-02-20 01:40:28)
    Type: 16(BGP4MP)
    Subtype: 5(BGP4MP_STATE_CHANGE_AS4)
    Length: 24
BGP4MP_STATE_CHANGE_AS4
    Peer AS Number: 100
    Local AS Number: 64512
    Interface Index: 0
    Address Family: 1(AFI_IPv4)
    Peer IP Address: 192.168.1.21
    Local IP Address: 192.168.1.100
    Old State: 5(OpenConfirm)
    New State: 6(Established)
---------------------------------------------------------------
MRT Header
    Timestamp: 1392828028(2014-02-20 01:40:28)
    Type: 16(BGP4MP)
    Subtype: 4(BGP4MP_MESSAGE_AS4)
    ...
```

**Comment by rohan718** [comment]
I really confused, as you know I don't have any experience in Ubunto , 
what's problem ?

![47](https://cloud.githubusercontent.com/assets/7647866/3091323/866e311e-e59b-11e3-81ed-8a7a56ee3eb6.png)

**Comment by t2mune** [comment]
Probably,

python ../mrtparse/examples/print_all.py latest-update.gz

**Comment by rohan718** [comment]
I should try this code : 

python ../mrtparse/examples/print_all.py latest-update.gz         

???

**Comment by t2mune** [comment]
Otherwise,

python $HOME/mrtparse/examples/print_all.py $HOME/Downloads/latest-update.gz

**Comment by rohan718** [comment]
Oh, it's Work , but for last question, for otherwise , for instance real BGP like 

"http://data.ris.ripe.net/rrc00"

what should I do ?

**Comment by rohan718** [comment]
Ok - I find my problem . thanks dear  t2mune & YoshiyukiYamauchi .

**Comment by t2mune** [comment]
You're welcome.
I hope that your project will go well.

**Comment by YoshiyukiYamauchi** [comment]
You're welcome.
Thank you for using mrtparse.

**Comment by t2mune** [comment]
Now I close this case.
