### ISSUE TITLE
potential bug: mrt2exabgp.py with BGP4MP_MESSAGE

### ISSUE THREAD

**Issue by danielseide** [t2mune/mrtparse#10]
used Version: 1.4
used mrt files: samples/quagga_bgp, one from RIPE RIS (updates dump), one from routeviews.org (updates dump)

observed behaviour: 
   without any flag (config format): prints the config header and footer but no static routes

   with (-A|-G) flag (api (grouping) format): prints nothing (and doesn't finish by itself; strg+c at 0% CPU over long time->other issue)

my guess:
   It seems like mrt2exabgp.py can't extract routes from the BGP4MP_MESSAGE type.

Regards,
Daniel

**Comment by danielseide** [comment]
just read the source code of mrt2exabgp.py:
seems like only TABLE_DUMP_V2 is supported

``` python
def mrt_type_check(m):
    if m.type != MRT_T['TABLE_DUMP_V2']:
           return 1
...
def conv_format(args, d):
...
    if mrt_type_check(m):
           continue
...
```

**Comment by t2mune** [comment]
As you wrote, it supports only "TABLE_DUMP_V2":sweat:
I would like to add a suuport for "BGP4_MP" and "TABLE_DUMP" soon.

**Comment by t2mune** [comment]
I added a support for "BGP4MP", "BGP4MP_ET", "TABLE_DUMP":smile:

**Comment by danielseide** [comment]
Thanks
