### ISSUE TITLE
Enhancement: mrt2exabgp.py (-A|-G) should finish by itself

### ISSUE THREAD

**Issue by danielseide** [t2mune/mrtparse#11]
used Version: 1.4
used mrt files: samples/quagga_bgp, samples/quagga_rib, one from RIPE RIS (updates dump), two from routeviews.org (updates dump, rib dump)

observed behaviour:
with (-A|-G) flag (api (grouping) format): mrt2exabgp.py doesn't finish by itself; it prints the correct routes with rib dumps (nothing for updates dumps->other issue) but it stays alive till the user finishes it with strg+c for example

Regards,
Daniel

**Comment by danielseide** [comment]
I just found https://github.com/YoshiyukiYamauchi/mrtparse/wiki/%5BExaBGP%5D-How-to-send-the-routes-using-the-API and https://github.com/YoshiyukiYamauchi/mrtparse/wiki/%5BExaBGP%5D-How-to-reduce-parsing-by-grouping-updates-with-the-same-attributes. Maybe therefore it's necessary that it doesn't finish.

By the way:
Your approach doesn't scale for multiple calls with huge amounts of prefixes (600k for example). At each call mrtparse has to parse 600k routes again (with python[not pypy] over one hour). Then better parse the routes once to a text file and copy it to the messages section of a python script like this:

``` python
#!/usr/bin/env python

import sys
import time

messages = [
'announce route 100.10.0.0/24 next-hop 192.168.0.27',
'announce route 200.20.0.0/24 next-hop 192.168.0.27'
]

time.sleep(2)

while messages:
    message = messages.pop(0)
    sys.stdout.write( message + '\n')
    sys.stdout.flush()
    time.sleep(1)

#Loop endlessly to allow ExaBGP to continue running
while True:
    time.sleep(1)

sys.stdin.readline()
```

this script could be imported in the config as usual:

``` python
...
process route_inject {
    run ./route_inject.run;
    encoder json;
}
...
```

**Comment by danielseide** [comment]
responsible part of mrt2exabgp.py:

``` python
    if flags & FLAG_T['API']:
        while True:
            time.sleep(1)
```

**Comment by t2mune** [comment]
> Maybe therefore it's necessary that it doesn't finish.

it's necessary as you wrote. Without a loop, it would continues processing.

> Then better parse the routes once to a text file and copy it to the messages section of a python script like this:

That's right. I will add a support for both ways.

**Comment by t2mune** [comment]
I added "-P" option to output ExaBGP API program:smile:

```
pypy mrt2exabgp.py -P -G latest-bview.gz > route_inject.run
```

And use the generated script as API program in the config.

```
group route_inject {
    neighbor 192.168.1.101 {
        router-id 127.0.0.2;
        local-address 127.0.0.2;
        local-as 64512;
        peer-as 65000;
        graceful-restart;

        process mrtparse {
            run /usr/bin/pypy ./route_inject.run;
        }
    }   
}
```

**Comment by danielseide** [comment]
perfect :)
