### ISSUE TITLE
ExaBGP API grouping format syntax change

### ISSUE THREAD

**Issue by danielseide** [t2mune/mrtparse#12]
The "announce attribute ..." syntax of the API grouping format was changed a little. It has to be "...attributes..." with s now in the current version.

Regards,
Daniel

**Comment by danielseide** [comment]
This applies only to exabgp master branch. 3.4.13 can handle "attribute" and "attributes".

**Comment by t2mune** [comment]
Thank you for letting us know:smile:
And really sorry for late reply...
I updated "mrt2exabgp.py".

**Comment by t2mune** [comment]
As of 3.4.16, it seems to handle both formats .

**Comment by danielseide** [comment]
As I wrote, this change was only in master branch. If the newer release versions support both versions mrtparse should also support both.

**Comment by t2mune** [comment]
Thnak you for your comment:exclamation:
I added a support for both syntax.

```
-G [NUM]       convert to ExaBGP API format and group updates with the same
             attributes for each spceified the number of prefixes using
             "annouce attributes ..." syntax (default: 1000000)
-g [NUM]       convert to ExaBGP API format and group updates with the same
             attributes for each spceified the number of prefixes using
             "annouce attribute ..." syntax (default: 1000000)
```

**Comment by danielseide** [comment]
Thank you
