### ISSUE TITLE
mrt2exabgp bails out with CRC error

### ISSUE THREAD

**Issue by jlixfeld** [t2mune/mrtparse#16]
Using http://data.ris.ripe.net/rrc00/latest-bview.gz:

root@pgen:/usr/local/etc/exabgp# /home/jlixfeld/mrtparse/examples/mrt2exabgp.py -A /home/jlixfeld/latest-bview.gz
announce route 0.0.0.0/0 origin IGP as-path [45896 3356 ] community [3356:3 3356:9 3356:575 3356:2003] next-hop 111.91.233.1
announce route ::/0 origin IGP as-path [29608 5511 5511 5511 5511 36925 ] med 11 community [5511:500 5511:518 5511:999 5511:5511 29608:30400] next-hop 2a01:678::2
announce route 1.0.4.0/22 origin IGP as-path [45896 4826 38803 56203 ] community [19996:2001] next-hop 111.91.233.1
announce route 1.0.4.0/24 origin IGP as-path [45896 4826 38803 56203 ] community [19996:2001] next-hop 111.91.233.1
...
...
...
Traceback (most recent call last):
  File "/home/jlixfeld/mrtparse/examples/mrt2exabgp.py", line 498, in <module>
    main()
  File "/home/jlixfeld/mrtparse/examples/mrt2exabgp.py", line 495, in main
    conv_format(args, flags, d)
  File "/home/jlixfeld/mrtparse/examples/mrt2exabgp.py", line 191, in conv_format
    for m in d:
  File "/usr/local/lib/python2.7/dist-packages/mrtparse-1.6-py2.7.egg/mrtparse/__init__.py", line 609, in __next__
    self.unpack_data()
  File "/usr/local/lib/python2.7/dist-packages/mrtparse-1.6-py2.7.egg/mrtparse/__init__.py", line 640, in unpack_data
    data = self.f.read(self.mrt.len)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x579c0579 != 0xd1fd5a7dL

I'm not well enough versed in Python to really be able to understand how to troubleshoot this.  Any assistance would be appreciated!

**Comment by t2mune** [comment]
Thank you for using mrtparse.

I tried downloading "latest-bview.gz" and running mrt2exabgp.py, but there was no  error.
Since I want to know when "latest-bview.gz" you used was generated, so please tell me the result of the following commands:

```
# /home/jlixfeld/mrtparse/examples/print_all.py /home/jlixfeld/latest-bview.gz | head -n 10
# md5sum /home/jlixfeld/latest-bview.gz
```

The following results should be displayed.
```
% ./print_all.py /home/t2mune/Downloads/latest-bview.gz | head -n 10
---------------------------------------------------------------
MRT Header
    Timestamp: 1520640000(2018-03-10 09:00:00)
    Type: 13(TABLE_DUMP_V2)
    Subtype: 1(PEER_INDEX_TABLE)
    Length: 567
PEER_INDEX_TABLE
    Collector: 193.0.4.28
    View Name Length: 0
    View Name:
% md5sum /home/t2mune/Downloads/latest-bview.gz
d6bbb904b4c559d5ebc8e2569495f6d4  /home/t2mune/Downloads/latest-bview.gz
```

**Comment by jlixfeld** [comment]
Hi,

I refreshed the copy of latest-bview.gz, and it works now.

Thank you for the pointer.

**Comment by t2mune** [comment]
I'm glad the problem was solved.
