### ISSUE TITLE
mrt2bgpdump.py crashes with Updates messages

### ISSUE THREAD

**Issue by julian10m** [t2mune/mrtparse#17]
Hi, 

First of all I want to say that I appreciate a lot this tool and that it's been helping me to read the BGP Updates messages. Nevertheless, I am having some trouble now. Here is what happens:

1) I am downloading one of the updates from: http://routeviews.org/bgpdata/2018.03/UPDATES/
For example: updates.20180322.1430.bz2

2) I run: python2.7 mrt2bgpdump.py -m -O output.txt updates.20180322.1430.bz2
And it just crashes with the following output:

**********************************************************
Traceback (most recent call last):
  File "mrt2bgpdump.py", line 302, in <module>
    main()
  File "mrt2bgpdump.py", line 298, in main
    b.bgp4mp(m, count)
  File "mrt2bgpdump.py", line 206, in bgp4mp
    self.bgp_attr(attr)
  File "mrt2bgpdump.py", line 268, in bgp_attr
    self.as4_aggr = '%d %s' % (attr.as4_aggr['asn'], attr.as4_aggr['ip'])
KeyError: 'ip'

**********************************************************
In line 267 and 268 we have:
   elif attr.type == BGP_ATTR_T['AS4_AGGREGATOR']:
            self.as4_aggr = '%d %s' % (attr.as4_aggr['asn'], attr.as4_aggr['ip'])

So for some reason the dictionary is not recognizing the key.

It seems that in all the previous tables I was using this attribute doesn't appear (at least I checked a couple and effectively it's not there). But now that I am taking Updates from routeviews, it creates some trouble. I commented the line after the if, and with a print I could see that the cases in which this attribute appears is quite low, but I did not know what else I could do, so I just leave you this message.

I hope I am not making any horrible mistake! 

Thanks for your time in advance,

Best regards,
Julian.

**Comment by t2mune** [comment]
Thank you for letting me know and using mrtparse !
It's a bug in "mrt2bgpdump.py".
[Since I fixed it](https://github.com/t2mune/mrtparse/commit/492df3d8dbcd5d7de02757a6ac2de972131f8acc), could you confirm whether it works ?

**Comment by julian10m** [comment]
thank youu!! it's working ok now :) 
(sorry for the delay in the answer)

**Comment by t2mune** [comment]
If there is any other problem, 
please feel free to contact me :smile:
