### ISSUE TITLE
TypeError: object of type 'NoneType' has no len() in a Route Views update file

### ISSUE THREAD

**Issue by rodrigodalri** [t2mune/mrtparse#19]
I'm running print_all.py for a Route Views update file and am getting the error below

File "/Users/rodrigodalri/Downloads/BGPstability/mrtparse/__init__.py", line 454, in chk_buf
    if len(self.buf) - self.p < n:
TypeError: object of type 'NoneType' has no len()

Any idea what that might be?

**Comment by t2mune** [comment]
Thank you for letting me know!
Could you tell me the URL of the Route Views update file where the error occurred?

**Comment by rodrigodalri** [comment]
This is an example of a file where the error occurs
http://archive.routeviews.org/route-views.linx/bgpdata/2019.01/UPDATES/updates.20190101.0000.bz2

I used bgpdump in two files, one that works and one that does not. The only apparent difference is in the Time field.

TIME: 05/01/19 00:15:00 - this file works correctly on mrtparse
TIME: 01/01/19 00:02:49.567611 - this does not work

Thanks.

**Comment by t2mune** [comment]
It's a bug, sorry...:cry:
[Since I fixed it](https://github.com/t2mune/mrtparse/commit/3a34fde53b5c2a65c11c0a559e06d18edb21e441), could you confirm whether it works ?

**Comment by rodrigodalri** [comment]
Yeah, it's working now!

Thanks.

**Comment by t2mune** [comment]
That's good to know:smile:
