### ISSUE TITLE
Bug in __init__.py line 930

### ISSUE THREAD

**Issue by giselle-briand** [t2mune/mrtparse#23]
Hi there,
In the __init__.py file there's a typo on line 930 when `path_seg['len']` is called. I believe it should be `path_seg['length']` instead, as there is no attribute `len` in a BGP message.

**Comment by andre-luiz-dos-santos** [comment]
Thank you @giselle-briand. I had this same error trying to read http://archive.routeviews.org/bgpdata/2020.11/UPDATES/updates.20201107.0300.bz2.

```
  File "/home/idea/.local/share/virtualenvs/python-g7NN1KAN/lib/python3.9/site-packages/mrtparse/__init__.py", line 930, in unpack_as4_path
    for _ in range(path_seg['len']):
KeyError: 'len'
```

**Comment by t2mune** [comment]
Hi,

Thank you very much for reporting this issue.
It's a typo, sorry.
